--create database in linux
CREATE TABLESPACE TPBD2
LOGGING
DATAFILE '/opt/oracle/oradata/TPBD2.dbf'
SIZE 40M REUSE
AUTOEXTEND ON NEXT 650 K MAXSIZE 80M;

/*
DESCOMENTAR ANTES DE ENTREGAR EL TRABAJO PRACTICO A LA PROFE
--create database in windows
CREATE TABLESPACE TPBD2
LOGGING
DATAFILE 'C:\oraclexe\app\oracle\oradata\TPBD2.dbf'
SIZE 40M REUSE
AUTOEXTEND ON NEXT 650 K MAXSIZE 80M;
*/
