--create database in linux
CREATE TABLESPACE BASED2TP
LOGGING
DATAFILE '/opt/oracle/oradata/BASED2TP.dbf'
SIZE 40M REUSE
AUTOEXTEND ON NEXT 650 K MAXSIZE 80M;

/*
DESCOMENTAR ANTES DE ENTREGAR EL TRABAJO PRACTICO A LA PROFE
--create database in windows
CREATE TABLESPACE BASED2TP
LOGGING
DATAFILE 'C:\oraclexe\app\oracle\oradata\BASED2TP.dbf'
SIZE 40M REUSE
AUTOEXTEND ON NEXT 650 K MAXSIZE 80M;
*/
