-- 8) Se requiere tener la vista materializada V_SOCIOS con la siguiente información
-- dada en el ejercitario. La vista se refrescará iniciando a partir de su creación
-- y posteriormente todos los días a las 22:00
CREATE MATERIALIZED VIEW V_SOCIOS	
BUILD IMMEDIATE
REFRESH START WITH (SYSDATE) NEXT (TRUNC(SYSDATE)+1) + 22/24
AS
SELECT 
	S.ID_SOCIO,
	S.CEDULA,
	S.NOMBRE || ' ' || S.APELLIDO Nombre_y_apellido,
	SUM(CA.SALDO_DISPONIBLE) Disponible,
	SUM(CASE CP.ESTADO WHEN 'A' THEN CC.MONTO_CUOTA ELSE 0 end) Deuda,
	SUM(CASE SC.TIPO_OBLIGACION WHEN 'A' THEN SC.TOTAL_A_ABONAR ELSE 0 end) Aporte
	FROM SOC_SOCIO S JOIN AHO_CUENTA_AHORRO CA ON S.ID_SOCIO = CA.ID_SOCIO
	JOIN CRE_SOLICITUD_PRESTAMOS CSP ON S.ID_SOCIO = CSP.SOCIO_DEUDOR
	JOIN CRE_PRESTAMOS CP ON CSP.ID_SOL_CRED = CP.ID_SOL_CRED
	JOIN CRE_CUOTAS CC ON CP.NRO_PRESTAMO = CC.NRO_PRESTAMO
	JOIN SOC_OBLIGACIONES SC ON SC.ID_SOCIO = S.ID_SOCIO
	GROUP BY  S.ID_SOCIO,
	S.CEDULA,
	S.NOMBRE || ' ' || S.APELLIDO;

-- 9)Cree una vista materializada V_PRESTAMOS que liste la situación de todos los socios
-- que tengan préstamos activos. La vista se actualizará cada hora
CREATE MATERIALIZED VIEW V_PRESTAMOS	
BUILD IMMEDIATE
REFRESH START WITH (SYSDATE) NEXT (TRUNC(SYSDATE)+1/24)
AS
SELECT S.NOMBRE||' '||S.APELLIDO "NOMBRE Y APELLIDO", 
SUM(DECODE(AC.INGRESO_GASTO, 'I',AD.IMPORTE,0)-DECODE(AC.INGRESO_GASTO,'G',AD.IMPORTE,0)) Ingresos,
SUM(DISTINCT AI.VALOR_FISCAL) "VALOR ACTIVOS", 
CP.V_SOCIOS "NRO PRESTAMO", 
sum(NVL(CA.SALDO_DISPONIBLE,0)) DISPONIBLE,
NVL(CP.MONTO_PRESTAMO,0) "MONTO PRESTAMO",
CP.FECHA_DESEMBOLSO "FECHA DESEBOLSO", 
MAX(CC.FECHA_PAGO) "ULTIMA FECHA DE PAGO",
SUM(DISTINCT(CASE WHEN CC.FECHA_PAGO IS NOT NULL THEN CC.MONTO_CUOTA - CC.INTERES_MORATORIO ELSE 0 END)) "MONTO CUOTAS PAGADAS",
SUM(DISTINCT(CASE WHEN CC.FECHA_PAGO IS NULL THEN CC.MONTO_CUOTA ELSE 0 END)) "MONTO CUOTAS PENDIENTES"
FROM SOC_SOCIO S
JOIN AHO_CUENTA_AHORRO CA
ON S.ID_SOCIO = CA.ID_SOCIO
JOIN CRE_SOLICITUD_PRESTAMOS CSP
ON S.ID_SOCIO = CSP.SOCIO_DEUDOR
JOIN CRE_PRESTAMOS CP
ON CP.ID_SOL_CRED=CSP.ID_SOL_CRED
JOIN ALD_INMUEBLES AI
ON AI.ID_SOCIO = S.ID_SOCIO
JOIN V_SOCIOS VS 
ON S.ID_SOCIO = VS.V_SOCIOS
JOIN ALD_DECLARACION_JURADA ADJ
ON ADJ.ID_SOCIO = S.ID_SOCIO
JOIN ALD_DETALLE_DECLARACION AD
ON AD.ID_DECLARACION = ADJ.ID_DECLARACION
JOIN ALD_CONCEPTOS AC
ON AC.ID_CONCEPTO = AD.ID_CONCEPTO
JOIN CRE_CUOTAS CC
ON CC.NRO_PRESTAMO = CP.NRO_PRESTAMO
group by S.ID_SOCIO, S.CEDULA, S.NOMBRE||' '||S.APELLIDO, CP.NRO_PRESTAMO, CP.MONTO_PRESTAMO, CP.FECHA_DESEMBOLSO;


CREATE OR REPLACE materialized view V_PRESTAMOS
refresh start with (sysdate) next (trunc(sysdate)+1/24)
SELECT DISTINCT S.NOMBRE||' '||S.APELLIDO as "Nombre y Apellido", 
SUM(DECODE(AC.INGRESO_GASTO, 'I',AD.IMPORTE,0) - DECODE(AC.INGRESO_GASTO,'G',AD.IMPORTE,0)) AS "Ingresos",
SUM(DISTINCT AI.VALOR_FISCAL) as "Valor Activos", 
sum(DISTINCT VS.DISPONIBLE) Disponible,  
CP.NRO_PRESTAMO as "Nro Prestamo",
CP.MONTO_PRESTAMO as "Monto Prestamo",
CP.FECHA_DESEMBOLSO as "Fecha Desembolso", 
MAX(CC.FECHA_PAGO) as "Ultima fecha de pago",
SUM(DISTINCT(CASE WHEN CC.FECHA_PAGO IS NOT NULL THEN CC.MONTO_CUOTA - CC.INTERES_MORATORIO ELSE 0 END)) "Monto Cuotas Pagadas",
SUM(DISTINCT(CASE WHEN CC.FECHA_PAGO IS NULL THEN CC.MONTO_CUOTA ELSE 0 END)) AS "Monto cuotas pendientes"
FROM SOC_SOCIO S
JOIN ALD_DECLARACION_JURADA ADJ
ON ADJ.ID_SOCIO = S.ID_SOCIO
JOIN ALD_DETALLE_DECLARACION AD
ON AD.ID_DECLARACION = ADJ.ID_DECLARACION
JOIN ALD_CONCEPTOS AC
ON AC.ID_CONCEPTO = AD.ID_CONCEPTO
JOIN ALD_INMUEBLES AI
ON AI.ID_SOCIO = S.ID_SOCIO
JOIN AHO_CUENTA_AHORRO CA
ON S.ID_SOCIO = CA.ID_SOCIO
JOIN CRE_SOLICITUD_PRESTAMOS CSP
ON S.ID_SOCIO = CSP.SOCIO_DEUDOR
JOIN CRE_PRESTAMOS CP
ON CP.ID_SOL_CRED=CSP.ID_SOL_CRED
JOIN CRE_CUOTAS CC
ON CC.NRO_PRESTAMO = CP.NRO_PRESTAMO
WHERE CP.ESTADO='A'
group by S.id_socio, S.cedula, S.NOMBRE||' '||S.APELLIDO, CP.NRO_PRESTAMO, CP.MONTO_PRESTAMO, CP.FECHA_DESEMBOLSO;