CREATE MATERIALIZED VIEW V_PRESTAMOS	
BUILD IMMEDIATE
REFRESH START WITH (SYSDATE) NEXT (TRUNC(SYSDATE)+1) + 59/60
AS
SELECT S.NOMBRE||' '||S.APELLIDO "NOMBRE Y APELLIDO", 
SUM(DECODE(AC.INGRESO_GASTO, 'I',AD.IMPORTE,0)-DECODE(AC.INGRESO_GASTO,'G',AD.IMPORTE,0)) Ingresos,
SUM(AI.VALOR_FISCAL) "Valor Activos", CP.NRO_PRESTAMO "NRO PRESTAMO", 
sum(NVL(CA.SALDO_DISPONIBLE,0)) DISPONIBLE,
NVL(CP.MONTO_PRESTAMO,0) "MONTO PRESTAMO",
CP.FECHA_DESEMBOLSO "FECHA DESEBOLSO", 
MAX(CC.FECHA_PAGO) "ULTIMA FECHA DE PAGO",
SUM((CASE WHEN CC.FECHA_PAGO IS NOT NULL THEN CC.MONTO_CUOTA ELSE 0 END) - CC.INTERES_MORATORIO) "MONTO CUOTAS PAGADAS",
SUM((CASE WHEN CC.FECHA_PAGO IS NULL THEN CC.MONTO_CUOTA ELSE 0 END)) "MONTO CUOTAS PENDIENTES"
FROM SOC_SOCIO S
JOIN AHO_CUENTA_AHORRO CA
ON S.ID_SOCIO = CA.ID_SOCIO
JOIN CRE_SOLICITUD_PRESTAMOS CSP
ON S.ID_SOCIO = CSP.SOCIO_DEUDOR
JOIN CRE_PRESTAMOS CP
ON CP.ID_SOL_CRED=CSP.ID_SOL_CRED
JOIN ALD_INMUEBLES AI
ON AI.ID_SOCIO = S.ID_SOCIO
JOIN ALD_DECLARACION_JURADA ADJ
ON ADJ.ID_SOCIO = S.ID_SOCIO
JOIN ALD_DETALLE_DECLARACION AD
ON AD.ID_DECLARACION = ADJ.ID_DECLARACION
JOIN ALD_CONCEPTOS AC
ON AC.ID_CONCEPTO = AD.ID_CONCEPTO
JOIN CRE_CUOTAS CC
ON CC.NRO_PRESTAMO = CP.NRO_PRESTAMO
WHERE CP.ESTADO='A' 
	AND AC.ID_CONCEPTO=(
    SELECT max(ID_CONCEPTO) FROM ALD_CONCEPTOS)
group by S.ID_SOCIO, S.CEDULA, S.NOMBRE||' '||S.APELLIDO, CP.NRO_PRESTAMO, CP.MONTO_PRESTAMO, CP.FECHA_DESEMBOLSO;