CREATE MATERIALIZED VIEW V_PRESTAMOS	
BUILD IMMEDIATE
REFRESH START WITH (SYSDATE) NEXT (TRUNC(SYSDATE)+1/24)
SELECT DISTINCT S.NOMBRE||' '||S.APELLIDO as "NOMBRE Y APELLIDO", 
SUM(DECODE(AC.INGRESO_GASTO, 'I',AD.IMPORTE,0) - DECODE(AC.INGRESO_GASTO,'G',AD.IMPORTE,0)) AS "INGRESOS",
SUM(DISTINCT AI.VALOR_FISCAL) as "VALORES ACTIVOS", 
sum(DISTINCT VS.DISPONIBLE) DISPONIBLE,  
CP.NRO_PRESTAMO as "NRO PRESTAMOS",
CP.MONTO_PRESTAMO as "MONTO PRESTAMO",
CP.FECHA_DESEMBOLSO as "FECHA DESEBOLSO", 
MAX(CC.FECHA_PAGO) as "ULTIMA FECHA DE PAGO",
SUM(DISTINCT(CASE WHEN CC.FECHA_PAGO IS NOT NULL THEN CC.MONTO_CUOTA - CC.INTERES_MORATORIO ELSE 0 END)) "MONTO CUOTAS PAGADAS",
SUM(DISTINCT(CASE WHEN CC.FECHA_PAGO IS NULL THEN CC.MONTO_CUOTA ELSE 0 END)) AS "MONTO CUOTAS PENDIENTES"
FROM SOC_SOCIO S
JOIN AHO_CUENTA_AHORRO CA
ON S.ID_SOCIO = CA.ID_SOCIO
JOIN CRE_SOLICITUD_PRESTAMOS CSP
ON S.ID_SOCIO = CSP.SOCIO_DEUDOR
JOIN CRE_PRESTAMOS CP
ON CP.ID_SOL_CRED=CSP.ID_SOL_CRED
JOIN ALD_INMUEBLES AI
ON AI.ID_SOCIO = S.ID_SOCIO
JOIN V_SOCIOS VS 
ON S.ID_SOCIO = VS.ID_SOCIO
JOIN ALD_DECLARACION_JURADA ADJ
ON ADJ.ID_SOCIO = S.ID_SOCIO
JOIN ALD_DETALLE_DECLARACION AD
ON AD.ID_DECLARACION = ADJ.ID_DECLARACION
JOIN ALD_CONCEPTOS AC
ON AC.ID_CONCEPTO = AD.ID_CONCEPTO
JOIN CRE_CUOTAS CC
ON CC.NRO_PRESTAMO = CP.NRO_PRESTAMO
group by S.ID_SOCIO, S.CEDULA, S.NOMBRE||' '||S.APELLIDO, CP.NRO_PRESTAMO, CP.MONTO_PRESTAMO, CP.FECHA_DESEMBOLSO;