INSERT INTO SOC_SOCIO 
	(ID_SOCIO, CEDULA, RUC, NOMBRE, APELLIDO, FECHA_NACIMIENTO, FECHA_INGRESO, DIRECCION, TELEFONO,
	EMAIL,SUSCRIPTO_NOVEDADES,ESTADO, FECHA_FALLECIMIENTO, FECHA_BAJA)
	SELECT seq_socio.nextval ,P.CEDULA, P.RUC, P.NOMBRE, P.APELLIDO, P.FECHA_NACIMIENTO, TRUNC(SYSDATE),
		P.DIRECCION, P.TELEFONO, P.CORREO_ELECTRONICO,'N','A', NULL, NULL 
	FROM B_PERSONAS P 
	WHERE P.CEDULA IS NOT NULL;


ALTER TABLE CRE_MODALIDAD_PRESTAMO
	MODIFY DESCRIPCION_MOD VARCHAR2(100);

