MERGE INTO AHO_CUENTA_AHORRO CA
USING (
SELECT CA.ID_CUENTA, 
(SELECT sum(MC.importe)
FROM AHO_CUENTA_AHORRO CA2 JOIN aho_movimientos_cuenta MC
ON CA2.ID_CUENTA = MC.ID_CUENTA
JOIN AHO_TIPO_MOVIMIENTO ATM
ON MC.ID_TIPO = ATM.ID_TIPO
where ATM.debito_credito='C'and CA.ID_CUENTA = CA2.ID_CUENTA) 
-
(SELECT sum(MC.importe) CA2.saldo_bloqueado
FROM AHO_CUENTA_AHORRO CA2 JOIN aho_movimientos_cuenta MC
ON CA2.ID_CUENTA = MC.ID_CUENTA
JOIN AHO_TIPO_MOVIMIENTO ATM
ON MC.ID_TIPO = ATM.ID_TIPO	
where ATM.debito_credito='D' and CA.ID_CUENTA = CA2.ID_CUENTA
group by CA2.ID_CUENTA, CA2.saldo_bloqueado) RESTA
FROM AHO_CUENTA_AHORRO CA JOIN aho_movimientos_cuenta MC
ON CA.ID_CUENTA = MC.ID_CUENTA
JOIN AHO_TIPO_MOVIMIENTO ATM
ON MC.ID_TIPO = ATM.ID_TIPO
group by CA.ID_CUENTA
) R
ON  CA.ID_CUENTA = R.ID_CUENTA)
WHEN matched THEN
	UPDATE SET CA.SALDO_DIPONIBLE = R.RESTA
;